module.exports = {
  FLOOR1_TIMER: 3000,

  FLOOR1_MIN_SIZE: 3,  //CHANGE THESE VALUES TO ADJUST DIFFICULTY
  FLOOR1_MAX_SIZE: 5,

  FLOOR2_LOG_COUNT: 10 //CHANGE THESE VALUES TO ADJUST DIFFICULTY
};