module.exports = {
  FLOOR1_TIMER: 3000,

  FLOOR1_MIN_SIZE: 3,
  FLOOR1_MAX_SIZE: 5,

  FLOOR2_LOG_COUNT: 10,

  MIN_PATH_LENGTH: 8,
  MAX_GENERATION_ATTEMPTS: 10000,

  GRID_SIZE: 15,
  PLAYER_LIVES: 3,

  PIT_MIN: 6,
  PIT_MAX: 10,

  WUMPUS_COUNT: 5,

  WALL_MIN: 40,
  WALL_MAX: 50,

  ARROWS: 5,

  SAFE_ROW: 0,

  WUMPUS_DETECTION_RADIUS: 5,
  WUMPUS_MOVE_INTERVAL: 1000
};